package com.pricegraphopener;

import com.google.common.annotations.VisibleForTesting;
import com.google.common.collect.HashMultimap;
import com.google.common.collect.Multimap;
import lombok.Getter;
import net.runelite.client.game.ItemVariationMapping;

import javax.annotation.Nullable;
import java.util.Collection;

import static net.runelite.api.ItemID.*;

@Getter
public enum IrreversibleItemMapping {

    // Raids items
    ITEM_KODAI_INSIGNIA(KODAI_INSIGNIA, KODAI_WAND),
    ITEM_MASORI_BODY(MASORI_BODY, MASORI_BODY_F),
    ITEM_MASORI_CHAPS(MASORI_CHAPS, MASORI_CHAPS_F),
    ITEM_MASORI_MASK(MASORI_MASK, MASORI_MASK_F),
    ITEM_AVERNIC_DEFENDER(AVERNIC_DEFENDER_HILT, AVERNIC_DEFENDER),

    // God Wars Dungeon items
    ITEM_ARMADYL_HILT(ARMADYL_HILT, ARMADYL_GODSWORD, ARMADYL_GODSWORD_OR),
    ITEM_BANDOS_HILT(BANDOS_HILT, BANDOS_GODSWORD, BANDOS_GODSWORD_OR),
    ITEM_SARADOMIN_HILT(SARADOMIN_HILT, SARADOMIN_GODSWORD, SARADOMIN_GODSWORD_OR),
    ITEM_ZAMORAK_HILT(ZAMORAK_HILT, ZAMORAK_GODSWORD, ZAMORAK_GODSWORD_OR),
    ITEM_ANCIENT_HILT(ANCIENT_HILT, ANCIENT_GODSWORD),
    ITEM_NIHIL_HORN(NIHIL_HORN, ZARYTE_CROSSBOW),
    ITEM_ARMADYL_CROSSBOW(ARMADYL_CROSSBOW, ZARYTE_CROSSBOW),
    ITEM_STAFF_OF_THE_DEAD(STAFF_OF_THE_DEAD, STAFF_OF_LIGHT),
    ITEM_SARADOMINS_LIGHT(SARADOMINS_LIGHT, STAFF_OF_LIGHT),
    ITEM_TORVA_PLATEBODY(TORVA_PLATEBODY_DAMAGED, TORVA_PLATEBODY, SANGUINE_TORVA_PLATEBODY),
    ITEM_TORVA_PLATELEGS(TORVA_PLATELEGS_DAMAGED, TORVA_PLATELEGS, SANGUINE_TORVA_PLATELEGS),
    ITEM_TORVA_FULL_HELM(TORVA_FULL_HELM_DAMAGED, TORVA_FULL_HELM, SANGUINE_TORVA_FULL_HELM),

    // Slayer boss drops
    ITEM_BLACK_TOURMALINE_CORE(BLACK_TOURMALINE_CORE, GUARDIAN_BOOTS),
    ITEM_SMOULDERING_STONE(SMOULDERING_STONE, INFERNAL_AXE, INFERNAL_AXE_OR, INFERNAL_AXE_UNCHARGED, INFERNAL_HARPOON, INFERNAL_HARPOON_OR, INFERNAL_HARPOON_UNCHARGED, INFERNAL_PICKAXE, INFERNAL_PICKAXE_OR, INFERNAL_PICKAXE_UNCHARGED),
    ITEM_DRAGON_AXE(DRAGON_AXE, INFERNAL_AXE, INFERNAL_AXE_OR, INFERNAL_AXE_UNCHARGED),
    ITEM_DRAGON_HARPOON(DRAGON_HARPOON, INFERNAL_HARPOON, INFERNAL_HARPOON_OR, INFERNAL_HARPOON_UNCHARGED),
    ITEM_DRAGON_PICKAXE(DRAGON_PICKAXE, INFERNAL_PICKAXE, INFERNAL_PICKAXE_OR, INFERNAL_PICKAXE_UNCHARGED),
    ITEM_RANGER_BOOTS(RANGER_BOOTS, PEGASIAN_BOOTS),
    ITEM_PEGASIAN_CRYSTAL(PEGASIAN_CRYSTAL, PEGASIAN_BOOTS),
    ITEM_ETERNAL_CRYSTAL(ETERNAL_CRYSTAL, ETERNAL_BOOTS),
    ITEM_INFINITY_BOOTS(INFINITY_BOOTS, ETERNAL_BOOTS),
    ITEM_DRAGON_BOOTS(DRAGON_BOOTS, PRIMORDIAL_BOOTS),
    ITEM_PRIMODIAL_CRYSTAL(PRIMORDIAL_CRYSTAL, PRIMORDIAL_BOOTS),
    ITEM_HYDRA_CLAW(HYDRAS_CLAW, DRAGON_HUNTER_LANCE),
    ITEM_ETERNAL_SLAYER_GEM(ETERNAL_GEM, SLAYER_RING_ETERNAL),
    ITEM_IMBUED_HEART(IMBUED_HEART, SATURATED_HEART),

    // Other boss drops
    ITEM_VENATOR_SHARD(VENATOR_SHARD, VENATOR_BOW, VENATOR_BOW_UNCHARGED),

    // Wilderness items
    ITEM_VOIDWAKER_HILT(VOIDWAKER_HILT, VOIDWAKER),
    ITEM_VOIDWAKER_GEM(VOIDWAKER_GEM, VOIDWAKER),
    ITEM_VOIDWAKER_BLADE(VOIDWAKER_BLADE, VOIDWAKER),
    ITEM_TANZANITE_FANG(TANZANITE_FANG, TOXIC_BLOWPIPE, BLAZING_BLOWPIPE,TOXIC_BLOWPIPE_EMPTY, BLAZING_BLOWPIPE_EMPTY),
    ITEM_CRAWS_BOW(CRAWS_BOW_U, WEBWEAVER_BOW, WEBWEAVER_BOW_U),
    ITEM_FANGS_OF_VENENATIS(FANGS_OF_VENENATIS, WEBWEAVER_BOW, WEBWEAVER_BOW_U),
    ITEM_THAMMARONS_SCEPTRE(THAMMARONS_SCEPTRE_U, ACCURSED_SCEPTRE_A, ACCURSED_SCEPTRE_U, ACCURSED_SCEPTRE_AU, ACCURSED_SCEPTRE),
    ITEM_SKULL_OF_VETION(SKULL_OF_VETION, ACCURSED_SCEPTRE_A, ACCURSED_SCEPTRE_U, ACCURSED_SCEPTRE_AU, ACCURSED_SCEPTRE),
    ITEM_VIGGORAS_CHAINMACE(VIGGORAS_CHAINMACE_U, URSINE_CHAINMACE, URSINE_CHAINMACE_U),
    ITEM_CLAWS_OF_CALLISTO(CLAWS_OF_CALLISTO, URSINE_CHAINMACE, URSINE_CHAINMACE_U),
    ITEM_ODIUM_SHARD_1(ODIUM_SHARD_1, ODIUM_WARD, ODIUM_WARD_12807),
    ITEM_ODIUM_SHARD_2(ODIUM_SHARD_2, ODIUM_WARD, ODIUM_WARD_12807),
    ITEM_ODIUM_SHARD_3(ODIUM_SHARD_3, ODIUM_WARD, ODIUM_WARD_12807),
    ITEM_MALEDICTION_SHARD_1(MALEDICTION_SHARD_1, MALEDICTION_WARD, MALEDICTION_WARD_12806),
    ITEM_MALEDICTION_SHARD_2(MALEDICTION_SHARD_2, MALEDICTION_WARD, MALEDICTION_WARD_12806),
    ITEM_MALEDICTION_SHARD_3(MALEDICTION_SHARD_3, MALEDICTION_WARD, MALEDICTION_WARD_12806),

    // Miscellaneous
    ITEM_BLOOD_SHARD(BLOOD_SHARD, AMULET_OF_BLOOD_FURY),
    ITEM_SERPENTINE_VISAGE(SERPENTINE_VISAGE, SERPENTINE_HELM, SERPENTINE_HELM_UNCHARGED, TANZANITE_HELM, TANZANITE_HELM_UNCHARGED, MAGMA_HELM, MAGMA_HELM_UNCHARGED),
    ITEM_ABYSSAL_WHIP(ABYSSAL_WHIP, ABYSSAL_TENTACLE),
    ITEM_DRAKES_CLAW(DRAKES_CLAW, BOOTS_OF_BRIMSTONE),
    ITEM_WYVERN_VISAGE(WYVERN_VISAGE, ANCIENT_WYVERN_SHIELD, ANCIENT_WYVERN_SHIELD_21634),
    ITEM_DRAGONIC_VISAGE(DRACONIC_VISAGE, DRAGONFIRE_SHIELD, DRAGONFIRE_SHIELD_11284),
    ITEM_BURNING_CLAW(BURNING_CLAW, BURNING_CLAWS),
    ITEM_TORMENTED_SYNAPSE(TORMENTED_SYNAPSE, EMBERLIGHT, PURGING_STAFF, SCORCHING_BOW),
    ITEM_ONYX(ONYX_AMULET, AMULET_OF_FURY, AMULET_OF_FURY_OR),
    ITEM_INGOT(CHROMIUM_INGOT, VENATOR_RING, MAGUS_RING, BELLATOR_RING, ULTOR_RING),



    ;




    @VisibleForTesting
    static final Multimap<Integer, IrreversibleItemMapping> MAPPINGS = HashMultimap.create();
    private final int tradeableItem;
    private final int[] untradeableItems;
    private final long quantity;
    private final boolean includeVariations;
    static
    {
        for (final IrreversibleItemMapping item : values())
        {
            for (int itemId : item.untradeableItems)
            {
                if (item.includeVariations)
                {
                    for (final Integer variation : ItemVariationMapping.getVariations(ItemVariationMapping.map(itemId)))
                    {
                        if (variation != item.tradeableItem)
                        {
                            MAPPINGS.put(variation, item);
                        }
                    }
                }
                else
                {
                    MAPPINGS.put(itemId, item);
                }
            }
        }
    }

    IrreversibleItemMapping(int tradeableItem, boolean includeVariations, long quantity, int... untradeableItems)
    {
        this.tradeableItem = tradeableItem;
        this.untradeableItems = untradeableItems;
        this.quantity = quantity;
        this.includeVariations = includeVariations;
    }

    IrreversibleItemMapping(int tradeableItem, long quantity, int... untradeableItems)
    {
        this(tradeableItem, false, quantity, untradeableItems);
    }

    IrreversibleItemMapping(int tradeableItem, int... untradeableItems)
    {
        this(tradeableItem, 1L, untradeableItems);
    }

    @Nullable
    public static Collection<IrreversibleItemMapping> map(int itemId)
    {
        final Collection<IrreversibleItemMapping> mapping = MAPPINGS.get(itemId);

        if (mapping.isEmpty())
        {
            return null;
        }

        return mapping;
    }
}
